<%@ Page Title="Squawker Manage" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Manage.aspx.cs" Inherits="SquawkerWebApplication.Manage" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">

    <asp:Table runat="server">
        <asp:TableRow>
            <asp:TableCell HorizontalAlign="Right">
                <asp:Label runat="server" Text="Post Id:"></asp:Label>
            </asp:TableCell>
            <asp:TableCell>
                <asp:TextBox runat="server" Width="150" ID="PostIdCriteria"></asp:TextBox>
            </asp:TableCell>
        </asp:TableRow>

        <asp:TableRow>
            <asp:TableCell HorizontalAlign="Right">
                <asp:Label runat="server" Text="User Id:"></asp:Label>
            </asp:TableCell>
            <asp:TableCell>
                <asp:TextBox runat="server" Width="150" ID="UserIdCriteria"></asp:TextBox>
            </asp:TableCell>
        </asp:TableRow>


        <asp:TableRow>
            <asp:TableCell HorizontalAlign="Right">
                <asp:Label runat="server" Text="Creation Date/Time:"></asp:Label>
            </asp:TableCell>
            <asp:TableCell>
                <asp:TextBox runat="server" Width="150" ID="DateCriteria"></asp:TextBox>
            </asp:TableCell>
        </asp:TableRow>

        <asp:TableRow>
            <asp:TableCell HorizontalAlign="Right">
                <asp:Label runat="server" Text="User's Name:"></asp:Label>
            </asp:TableCell>
            <asp:TableCell>
                <asp:TextBox runat="server" Width="150" ID="UsernameCriteria"></asp:TextBox>
            </asp:TableCell>
        </asp:TableRow>

        <asp:TableRow>
            <asp:TableCell HorizontalAlign="Right">
                <asp:Label runat="server" Text="User's Email:"></asp:Label>
            </asp:TableCell>
            <asp:TableCell>
                <asp:TextBox runat="server" Width="150" ID="EmailCriteria"></asp:TextBox>
            </asp:TableCell>
        </asp:TableRow>

        <asp:TableRow>
            <asp:TableCell HorizontalAlign="Right">
                <asp:Label runat="server" Text="Post Content:"></asp:Label>
            </asp:TableCell>
            <asp:TableCell>
                <asp:TextBox runat="server" Width="150" ID="ContentCriteria"></asp:TextBox>
            </asp:TableCell>
        </asp:TableRow>

        <asp:TableRow>
            <asp:TableCell HorizontalAlign="Right">
                <asp:Label runat="server" Text="Length of Post:"></asp:Label>
            </asp:TableCell>
            <asp:TableCell>
                <asp:TextBox runat="server" Width="150" ID="LengthCriteria"></asp:TextBox>
            </asp:TableCell>
        </asp:TableRow>
        <asp:TableRow>
            <asp:TableCell>
                <asp:Label runat="server"></asp:Label>
            </asp:TableCell>
            <asp:TableCell HorizontalAlign="Right">
                <asp:Button runat="server" Width="100%" ID="Search" Text="Search" OnClick="Search_Click" /><br />
                <asp:Button runat="server" Width="100%" ID="Clear" Text="Clear" OnClick="Clear_Click" />
            </asp:TableCell>
        </asp:TableRow>
    </asp:Table>

    <br />
    <br />

    <asp:Button runat="server" ID="GenerateDummyRow" Text="Insert Dummy Row:" OnClick="GenerateDummyRow_Click" />
    <asp:GridView
        runat="server"
        ID="ManageGridView"
        AutoGenerateColumns="true"
        AutoGenerateEditButton="true"
        AutoGenerateDeleteButton="true"
        OnRowDeleting="ManageGridView_RowDeleting"
        OnRowEditing="ManageGridView_RowEditing"
        OnRowCancelingEdit="ManageGridView_RowCancelingEdit"
        OnRowUpdating="ManageGridView_RowUpdating">
    </asp:GridView>

</asp:Content>
